networks:
  frontend-network:
    driver: bridge

services:
  frontend:
    build: { context: ., dockerfile: Dockerfile.dev }
    ports: ["5173:5173"]
    env_file: ./.env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - frontend-network