# MyPerseverance/frontend/docker-compose.yml
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network