# MyPerseverance/backend/docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # This single line loads all variables from your .env file
    env_file:
      - ./.env
    # We only define variables here that are NOT in the .env file
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:14.18
    # Using env_file here is also clean and consistent
    env_file:
      - ./.env
    volumes:
      # This volume is defined in your root docker-compose.yml
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"