# File: backend/docker-compose.yml
services:
  db:
    image: 'postgres:16'
    ports: ["5432:5432"]
    # Add the env_file here to provide environment variables
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  backend:
    build: { context: ., dockerfile: Dockerfile }
    ports: ["8080:8080"]
    # Add the env_file here to provide environment variables
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_ORIGIN_URL: ${CLIENT_ORIGIN_URL}
    volumes:
      - ./src/main:/app/src/main
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-network
