networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:

services:
  db:
    image: 'postgres:16'
    ports:
      - "5432:5432"
    env_file:
      - ./.env            # Good to specify as list
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"] # Use env var here too
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: local
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_ORIGIN_URL: ${CLIENT_ORIGIN_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-network
